// <auto-generated />
using Lab5.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab5.Migrations.FluentUserDb
{
    [DbContext(typeof(FluentUserDbContext))]
    partial class FluentUserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Lab5.Models.FluentUser", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER")
                        .HasColumnName("age_of_user");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_FirstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_LastName");

                    b.Property<int>("title")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("FluentUsers");
                });

            modelBuilder.Entity("Lab5.Models.FluentUserExtension", b =>
                {
                    b.Property<int>("FluentUserID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Title")
                        .HasColumnType("INTEGER");

                    b.HasKey("FluentUserID");

                    b.ToTable("FluentUserExtension");
                });

            modelBuilder.Entity("Lab5.Models.FluentUserExtension", b =>
                {
                    b.HasOne("Lab5.Models.FluentUser", null)
                        .WithOne("Extension")
                        .HasForeignKey("Lab5.Models.FluentUserExtension", "FluentUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lab5.Models.FluentUser", b =>
                {
                    b.Navigation("Extension");
                });
#pragma warning restore 612, 618
        }
    }
}
